version: "3.0"
    
services:
  database:
    image: ovalerio/automation_playground_db:v1
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    image: ovalerio/automation_playground_woocommerce:v1
    depends_on:
      - database
    ports:
      - "8085:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content

volumes:
  wordpress:
  db_data: